/**
 * TCHOKOS SARL — products.js
 * Pour ajouter un produit : copier un objet et modifier les champs.
 * Pour ajouter une catégorie : ajouter une entrée dans CATEGORIES et des produits avec le bon cat/subcat.
 */

const CATEGORIES = [
  { id: 'chaussures-femme',  label: 'Chaussures Femme',  subcats: ['Sneakers', 'Sandales', 'Babouches', 'Ballerines', 'Talons'] },
  { id: 'chaussures-homme',  label: 'Chaussures Homme',  subcats: ['Tennis', 'Derby', 'Mocassins', 'Babouches'] },
  { id: 'textile',           label: 'Textile',            subcats: ['Draps', 'Casquettes', 'Sacs', 'Vêtements'] },
  { id: 'electromenager',    label: 'Électroménager',     subcats: ['Cuisine'] },
  { id: 'maison',            label: 'Maison & Déco',      subcats: ['Coussins', 'Napperons', 'Tapis'] },
  { id: 'parfums',           label: 'Parfums',            subcats: ['Femme', 'Homme', 'Mixte'] },
];

const PRODUCTS = [
  // ── CHAUSSURES FEMME ──────────────────────────────────────
  {
    id: 1,
    name: 'Sneaker Damier Blanc/Lavande',
    cat: 'chaussures-femme', subcat: 'Sneakers',
    price: 15000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/sneaker-femme-damier.jpg',
    sizes: ['36','37','38','39','40','41'],
    description: 'Sneaker tendance motif damier blanc et lavande. Semelle caoutchouc naturel gum. Légère et confortable pour un look urbain au quotidien.',
    inStock: true,
  },
  {
    id: 2,
    name: 'Sandales Compensées Multicolore',
    cat: 'chaussures-femme', subcat: 'Sandales',
    price: 12000, badge: 'Tendance', badgeType: 'badge-gold',
    image: '../images/sandales-femme-multicolore.jpg',
    sizes: ['36','37','38','39','40'],
    description: 'Sandales compensées à bandes multicolores incrustées. Semelle pailletée noire. Idéale pour soirées, mariages et sorties.',
    inStock: true,
  },
  {
    id: 3,
    name: 'Mules Plateforme Noir/Rouge',
    cat: 'chaussures-femme', subcat: 'Babouches',
    price: 10000, badge: '', badgeType: '',
    image: '../images/mules-femme-noir-rouge.jpg',
    sizes: ['36','37','38','39','40','41'],
    description: 'Mules plateforme motif signature grec, bande rouge et noire. Semelle noire épaisse. Look luxueux au quotidien.',
    inStock: true,
  },
  {
    id: 4,
    name: 'Mules Plateforme Camel/Blanc',
    cat: 'chaussures-femme', subcat: 'Babouches',
    price: 10000, badge: '', badgeType: '',
    image: '../images/mules-femme-camel.jpg',
    sizes: ['36','37','38','39','40'],
    description: 'Mules plateforme finition camel et blanc, logo brodé double C. Légèreté et élégance garanties.',
    inStock: true,
  },
  {
    id: 6,
    name: 'Ballerine Vernis Blanc à Boucle',
    cat: 'chaussures-femme', subcat: 'Ballerines',
    price: 9000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/ballerine-femme-blanche-boucle.jpg',
    sizes: ['36','37','38','39','40'],
    description: 'Ballerine vernis blanc avec boucle rectangulaire argentée sur l\'empeigne. Talon légèrement compensé. Élégante pour le bureau ou les sorties.',
    inStock: true,
  },
  {
    id: 7,
    name: 'Sandales Plates Tressées Noir',
    cat: 'chaussures-femme', subcat: 'Sandales',
    price: 8500, badge: '', badgeType: '',
    image: '../images/sandales-femme-tresse-noir.jpg',
    sizes: ['36','37','38','39','40','41'],
    description: 'Sandales plates en cuir tressé noir, bout carré ouvert. Style minimaliste et chic. Confort absolu pour usage quotidien.',
    inStock: true,
  },

  // ── CHAUSSURES HOMME ──────────────────────────────────────
  {
    id: 5,
    name: 'Derby Cuir Noir Semelle Crantée',
    cat: 'chaussures-homme', subcat: 'Derby',
    price: 18000, badge: 'Bestseller', badgeType: 'badge-dark',
    image: '../images/derby-homme-noir.jpg',
    sizes: ['40','41','42','43','44','45'],
    description: 'Derby en cuir véritable noir, semelle crantée ultra-robuste. Le classique indémodable. Coutures blanches contrastées.',
    inStock: true,
  },
  {
    id: 8,
    name: 'Babouche Cuir Texturé Marron',
    cat: 'chaussures-homme', subcat: 'Babouches',
    price: 9000, badge: '', badgeType: '',
    image: '../images/babouche-homme-marron.jpg',
    sizes: ['40','41','42','43','44'],
    description: 'Babouche homme cuir texturé marron foncé, boucle métal argenté. Confort absolu pour journées longues.',
    inStock: true,
  },
  {
    id: 9,
    name: 'Sneaker Adidas Running Gris/Noir',
    cat: 'chaussures-homme', subcat: 'Tennis',
    price: 16000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/sneaker-homme-adidas.jpg',
    sizes: ['40','41','42','43','44','45'],
    description: 'Sneaker running bi-matière gris anthracite et noir, semelle Boost amortissante. Performance et style urbain.',
    inStock: true,
  },
  {
    id: 10,
    name: 'Nike SB Dunk Low Bleu Marine',
    cat: 'chaussures-homme', subcat: 'Tennis',
    price: 17000, badge: '', badgeType: '',
    image: '../images/sneaker-homme-nike.jpg',
    sizes: ['40','41','42','43','44','45'],
    description: 'Nike SB Dunk Low coloris bleu marine et orange. Semelle gum. Classique du skatewear revisité.',
    inStock: true,
  },
  {
    id: 19,
    name: 'Mocassin Cuir Verni Marron — Boss',
    cat: 'chaussures-homme', subcat: 'Mocassins',
    price: 20000, badge: 'Premium', badgeType: 'badge-gold',
    image: '../images/mocassin-homme-boss-marron.jpg',
    sizes: ['40','41','42','43','44','45'],
    description: 'Mocassin cuir verni deux tons marron, motif croco sur l\'empeigne avec logo Boss. Semelle crantée beige. Allure chic et décontractée.',
    inStock: true,
  },
  {
    id: 20,
    name: 'Mocassin Vernis Noir Boucle — Gucci',
    cat: 'chaussures-homme', subcat: 'Mocassins',
    price: 19000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/mocassin-homme-gucci-noir.jpg',
    sizes: ['40','41','42','43','44','45'],
    description: 'Mocassin cuir verni noir brillant avec boucle métal gunmetal. Semelle crantée camel. Silhouette urbaine et sophistiquée.',
    inStock: true,
  },
  {
    id: 21,
    name: 'Sneaker Trail The North Face Kaki/Jaune',
    cat: 'chaussures-homme', subcat: 'Tennis',
    price: 18000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/sneaker-homme-northface-kaki.jpg',
    sizes: ['40','41','42','43','44','45'],
    description: 'Sneaker trail The North Face Mesa, coloris kaki olive et jaune vif. Tige mesh respirante. Idéal sport et usage urbain.',
    inStock: true,
  },
  {
    id: 22,
    name: 'Mocassin Suède Bleu Marine/Orange',
    cat: 'chaussures-homme', subcat: 'Mocassins',
    price: 17000, badge: 'Tendance', badgeType: 'badge-gold',
    image: '../images/mocassin-homme-suede-bleu.jpg',
    sizes: ['40','41','42','43','44','45'],
    description: 'Mocassin en daim bleu marine, intérieur et liseré orange vif. Semelle plateforme blanche ultra-légère. Must-have de la saison.',
    inStock: true,
  },

  // ── TEXTILE ───────────────────────────────────────────────
  {
    id: 11,
    name: 'Drap Fleuri Bleu — 3 Places',
    cat: 'textile', subcat: 'Draps',
    price: 25000, badge: '', badgeType: '',
    image: '../images/drap-fleurs-bleu.jpg',
    sizes: [],
    description: 'Drap 3 places coton 100%, motif floral bleu. Contenu : 2 draps 240×260 cm + 2 taies 60×80 cm. Marque Dalia.',
    inStock: true,
  },
  {
    id: 12,
    name: 'Drap Géométrique Coloré — 3 Places',
    cat: 'textile', subcat: 'Draps',
    price: 25000, badge: '', badgeType: '',
    image: '../images/drap-geometrique.jpg',
    sizes: [],
    description: 'Drap 3 places coton 100%, motif géométrique multicolore. Contenu : 2 draps 240×260 cm + 2 taies 60×80 cm. Marque Dalia.',
    inStock: true,
  },
  {
    id: 13,
    name: 'Casquettes Alo Classic (lot de 2)',
    cat: 'textile', subcat: 'Casquettes',
    price: 8000, badge: '', badgeType: '',
    image: '../images/casquettes-alo-classic.jpg',
    sizes: [],
    description: 'Lot de 2 casquettes Alo brodées, coloris camel et noir. Tissu coton épais, réglable.',
    inStock: true,
  },
  {
    id: 14,
    name: 'Casquettes Alo Distressed (lot de 2)',
    cat: 'textile', subcat: 'Casquettes',
    price: 8000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/casquettes-alo-distressed.jpg',
    sizes: [],
    description: 'Lot de 2 casquettes Alo effet usé distressed, blanc et noir marine. Look vintage et urbain.',
    inStock: true,
  },
  {
    id: 15,
    name: 'Sac à Dos Tchokos Urban Gris',
    cat: 'textile', subcat: 'Sacs',
    price: 14000, badge: 'Made in Africa', badgeType: 'badge-gold',
    image: '../images/sac-gris-urban.jpg',
    sizes: [],
    description: 'Sac à dos urbain gris anthracite, badge Tchokos doré. Multi-compartiments, fermetures dorées. ~25L.',
    inStock: true,
  },
  {
    id: 16,
    name: 'Sac à Dos Wax Bleu/Orange',
    cat: 'textile', subcat: 'Sacs',
    price: 12000, badge: 'Made in Africa', badgeType: 'badge-gold',
    image: '../images/sac-wax-bleu-orange.jpg',
    sizes: [],
    description: 'Sac à dos tissu wax africain bleu et orange, logo Tchokos brodé. Fait main, pièce unique.',
    inStock: true,
  },
  {
    id: 17,
    name: 'Sac à Dos Wax Kaki/Bogolan',
    cat: 'textile', subcat: 'Sacs',
    price: 12000, badge: 'Made in Africa', badgeType: 'badge-gold',
    image: '../images/sac-wax-kaki.jpg',
    sizes: [],
    description: 'Sac à dos tissu kaki avec panneau bogolan africain jaune et bordeaux. Bretelles rembourrées. Fait main.',
    inStock: true,
  },
  {
    id: 23,
    name: 'Sac Bandoulière Homme Cuir Jeep — Noir',
    cat: 'textile', subcat: 'Sacs',
    price: 10000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/sac-bandouliere-homme-jeep.jpg',
    sizes: [],
    description: 'Sac bandoulière homme simili cuir noir, logo Jeep. Multi-poches zippées, sangle réglable. Idéal sorties et voyages.',
    inStock: true,
  },
  {
    id: 24,
    name: 'Sac à Main Femme Raphia Multicolore',
    cat: 'textile', subcat: 'Sacs',
    price: 11000, badge: 'Tendance', badgeType: 'badge-gold',
    image: '../images/sac-a-main-femme-raphia-multicolore.jpg',
    sizes: [],
    description: 'Sac à main en raphia tressé rayures multicolores. Fermoir métal argenté logo F. Poignée courte + bandoulière amovible.',
    inStock: true,
  },
  {
    id: 25,
    name: 'Ensemble Chemise + Short Rayures Multicolore',
    cat: 'textile', subcat: 'Vêtements',
    price: 13000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/ensemble-chemise-short-rayures-multicolore.jpg',
    sizes: ['S','M','L','XL','XXL'],
    description: 'Ensemble 2 pièces : chemise manches courtes + short assorti. Rayures vert, bordeaux, bleu, blanc. Label Tchokos.',
    inStock: true,
  },
  {
    id: 26,
    name: 'Ensemble Polo + Short Rayures Noir/Blanc',
    cat: 'textile', subcat: 'Vêtements',
    price: 13000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/ensemble-polo-short-rayures-noir-blanc.jpg',
    sizes: ['S','M','L','XL','XXL'],
    description: 'Ensemble 2 pièces : polo col zippé + short assorti. Rayures larges noir et blanc. Label Tchokos. Style sport décontracté.',
    inStock: true,
  },
  {
    id: 27,
    name: 'T-Shirt Oversize Celine Studs — Noir',
    cat: 'textile', subcat: 'Vêtements',
    price: 9000, badge: 'Tendance', badgeType: 'badge-gold',
    image: '../images/tshirt-oversize-celine-studs-noir.jpg',
    sizes: ['S','M','L','XL','XXL'],
    description: 'T-shirt oversize noir avec inscription CELINE en studs dorés. Coton doux, coupe ample. Style streetwear premium.',
    inStock: true,
  },
  {
    id: 28,
    name: 'T-Shirt Oversize Celine Studs — Rose',
    cat: 'textile', subcat: 'Vêtements',
    price: 9000, badge: 'Tendance', badgeType: 'badge-gold',
    image: '../images/tshirt-oversize-celine-studs-rose.jpg',
    sizes: ['S','M','L','XL','XXL'],
    description: 'T-shirt oversize rose bonbon avec inscription CELINE en studs dorés. Coton doux, coupe ample.',
    inStock: true,
  },

  // ── ÉLECTROMÉNAGER ────────────────────────────────────────
  {
    id: 18,
    name: 'Grill / Sandwich Maker Oarona 750W',
    cat: 'electromenager', subcat: 'Cuisine',
    price: 11000, badge: 'Promo', badgeType: 'badge-red',
    image: '../images/grill-maker.jpg',
    sizes: [],
    description: 'Appareil 3-en-1 : grill, sandwich maker et waffle maker. 750W, revêtement anti-adhésif. Modèle LV-885.',
    inStock: true,
  },
  {
    id: 29,
    name: 'Broyeur Multifonction Hoffmans 1000W',
    cat: 'electromenager', subcat: 'Cuisine',
    price: 13000, badge: '', badgeType: '',
    image: '../images/broyeur-hoffmans.jpg',
    sizes: [],
    description: 'Broyeur professionnel inox 150g, 1000W. Garantie 18 mois. Idéal épices, café, céréales. Modèle HM-9081.',
    inStock: true,
  },
  {
    id: 30,
    name: 'Hachoir Électrique Hoffmans 1200W',
    cat: 'electromenager', subcat: 'Cuisine',
    price: 15000, badge: '', badgeType: '',
    image: '../images/hachoir-hoffmans.jpg',
    sizes: [],
    description: 'Hachoir 2L, 1200W, bol inox SUS304. Hache viandes et légumes. 12 mois de garantie. Modèle HM-8861.',
    inStock: true,
  },

  // ── MAISON & DÉCO ─────────────────────────────────────────
  {
    id: 31,
    name: 'Coussin Tête de Lit Velours Terracotta',
    cat: 'maison', subcat: 'Coussins',
    price: 22000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/coussin-tete-de-lit-velours-terracotta.jpg',
    sizes: [],
    description: 'Grand coussin triangulaire tête de lit velours matelassé terracotta, liseré blanc voile. Rembourrage moelleux. Touche chic pour votre chambre.',
    inStock: true,
  },
  {
    id: 32,
    name: 'Napperon Dentelle Ronde Bleu Pastel',
    cat: 'maison', subcat: 'Napperons',
    price: 3500, badge: '', badgeType: '',
    image: '../images/napperon-dentelle-rond-bleu.jpg',
    sizes: [],
    description: 'Napperon rond dentelle ajourée bleu pastel, motifs floraux et géométriques. Protège meubles et surfaces avec élégance.',
    inStock: true,
  },
  {
    id: 33,
    name: 'Napperons Brodés Or (lot de 2)',
    cat: 'maison', subcat: 'Napperons',
    price: 6000, badge: '', badgeType: '',
    image: '../images/napperons-brodes-dore-lot2.jpg',
    sizes: [],
    description: 'Lot de 2 napperons rectangulaires brodés fils dorés sur fond blanc. Motifs fleurs et arabesques orientaux.',
    inStock: true,
  },
  {
    id: 34,
    name: 'Tapis Enfant Sweet Bear Multicolore',
    cat: 'maison', subcat: 'Tapis',
    price: 18000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/tapis-enfant-cartoon-sweet-bear.jpg',
    sizes: [],
    description: 'Grand tapis de jeu enfant multicolore personnages cartoon Sweet Bear et animaux. Doux et lavable. Parfait pour chambre d\'enfant.',
    inStock: true,
  },
  {
    id: 35,
    name: 'Tapis Oriental Rouge/Or',
    cat: 'maison', subcat: 'Tapis',
    price: 20000, badge: '', badgeType: '',
    image: '../images/tapis-oriental-rouge-or.jpg',
    sizes: [],
    description: 'Grand tapis oriental fond rouge, motifs étoiles et arabesques dorés et verts. Tissage dense. Apporte chaleur et élégance à votre intérieur.',
    inStock: true,
  },

  // ── PARFUMS ───────────────────────────────────────────────
  {
    id: 36,
    name: 'Eau de Parfum Pink Love — 100ml',
    cat: 'parfums', subcat: 'Femme',
    price: 7000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/parfum-pink-love-edp-100ml.jpg',
    sizes: [],
    description: 'Eau de parfum Pink Love, 100ml, 80% Vol. Notes florales et sucrées. Livré dans sa pochette cadeau.',
    inStock: true,
  },
  {
    id: 37,
    name: 'Eau de Parfum Pure Black — 100ml',
    cat: 'parfums', subcat: 'Homme',
    price: 7000, badge: 'Nouveau', badgeType: 'badge-red',
    image: '../images/parfum-pure-black-edp-100ml.jpg',
    sizes: [],
    description: 'Eau de parfum Pure Black pour homme, 100ml. Notes boisées et musquées intenses. Flacon mat noir avec pochette incluse.',
    inStock: true,
  },
  {
    id: 38,
    name: 'Eau de Parfum Poison — 100ml',
    cat: 'parfums', subcat: 'Mixte',
    price: 7000, badge: '', badgeType: '',
    image: '../images/parfum-poison-edp-100ml.jpg',
    sizes: [],
    description: 'Eau de parfum Poison, 100ml. Fragrance envoûtante et mystérieuse. Flacon carré mat noir avec pochette assortie.',
    inStock: true,
  },
];

/** Formate un prix en FCFA */
function formatPrice(price) {
  return price.toLocaleString('fr-FR') + ' FCFA';
}

/** Récupère un produit par son ID */
function getProductById(id) {
  return PRODUCTS.find(p => p.id === parseInt(id));
}

/** Filtre les produits par catégorie */
function getProductsByCategory(catId) {
  if (!catId || catId === 'tous') return PRODUCTS;
  return PRODUCTS.filter(p => p.cat === catId);
}
